package com.haithamassoli.naqi.audio

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.util.Random
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.log10
import kotlin.math.sin

/**
 * JVM unit tests for the M2 out-of-graph DSP: the radix-2 [Fft] and the demucs [Stft] forward/inverse.
 *
 * Pure JVM (no Android, no ORT). The small-config golden (`/dsp/stft_small.json`, generated by
 * `scripts/stft_golden.py`) is an independent numpy f64 reference; the port runs f32 data, so the
 * golden comparisons use atol 1e-4 (the measured f32-vs-f64 gap is ~2e-7).
 */
class DspTest {

    // ---- (1) FFT vs analytic DFT ----

    @Test fun fftImpulseIsFlatSpectrum() {
        val n = 64
        val re = FloatArray(n).also { it[0] = 1f }   // δ[0] → X[k] = 1 for all k
        val im = FloatArray(n)
        Fft.forward(re, im)
        for (k in 0 until n) {
            assertEquals(1.0, re[k].toDouble(), 1e-5)
            assertEquals(0.0, im[k].toDouble(), 1e-5)
        }
    }

    @Test fun fftPureToneHasTwoRealPeaks() {
        val n = 64
        val k0 = 5
        val re = FloatArray(n) { cos(2.0 * PI * k0 * it / n).toFloat() }   // real cosine → peaks at k0, n-k0
        val im = FloatArray(n)
        Fft.forward(re, im)
        for (k in 0 until n) {
            val expected = if (k == k0 || k == n - k0) n / 2.0 else 0.0
            assertEquals(expected, re[k].toDouble(), 1e-3)
            assertEquals(0.0, im[k].toDouble(), 1e-3)
        }
    }

    @Test fun fftMatchesNaiveDft() {
        val n = 64
        val rng = Random(1L)
        val re = FloatArray(n) { (rng.nextDouble() * 2 - 1).toFloat() }
        val im = FloatArray(n) { (rng.nextDouble() * 2 - 1).toFloat() }
        val (refRe, refIm) = naiveDft(re, im)
        Fft.forward(re, im)
        for (k in 0 until n) {
            assertEquals(refRe[k], re[k].toDouble(), 1e-3)
            assertEquals(refIm[k], im[k].toDouble(), 1e-3)
        }
    }

    @Test fun fftInverseRoundTrips() {
        val n = 4096
        val rng = Random(2L)
        val re0 = FloatArray(n) { (rng.nextDouble() * 2 - 1).toFloat() }
        val im0 = FloatArray(n) { (rng.nextDouble() * 2 - 1).toFloat() }
        val re = re0.copyOf()
        val im = im0.copyOf()
        Fft.forward(re, im)
        Fft.inverse(re, im)   // must fold in 1/n exactly once
        for (i in 0 until n) {
            assertEquals(re0[i].toDouble(), re[i].toDouble(), 1e-4)
            assertEquals(im0[i].toDouble(), im[i].toDouble(), 1e-4)
        }
    }

    // ---- (2) small-config golden (nfft=64, hop=16, T=4123) ----

    @Test fun stftForwardMatchesGolden() {
        val g = golden()
        val cac = Stft(g.nfft, g.hop).forward(g.input0, g.input1, g.t)
        assertEquals(g.cac.size, cac.size)
        assertMaxAbsDiff(g.cac, cac, 1e-4)
    }

    @Test fun stftInverseMatchesGolden() {
        val g = golden()
        val cac = FloatArray(g.cac.size) { g.cac[it].toFloat() }   // feed the untouched golden cac
        val out0 = FloatArray(g.t)
        val out1 = FloatArray(g.t)
        Stft(g.nfft, g.hop).inverse(cac, g.t, out0, out1)
        assertMaxAbsDiff(g.roundtrip0, out0, 1e-4)
        assertMaxAbsDiff(g.roundtrip1, out1, 1e-4)
    }

    // ---- (3) full-size roundtrip (Stft(4096, 1024) on T = 343_980) ----

    @Test fun fullSizeInteriorRoundTripHighSnr() {
        val t = 343_980
        val x0 = bandLimited(t, seed = 11L)
        val x1 = bandLimited(t, seed = 12L)
        val stft = Stft(4096, 1024)
        val cac = stft.forward(x0, x1, t)
        val out0 = FloatArray(t)
        val out1 = FloatArray(t)
        stft.inverse(cac, t, out0, out1)
        // The model deliberately drops the Nyquist bin and zeroes the 4 boundary frames (dsp-spec §2b),
        // so a full-band (white) signal cannot round-trip and the ~1536-sample edges are intentional loss.
        // A band-limited probe's INTERIOR reconstructs to the f32 floor (~144 dB); assert the plan's 80 dB.
        val guard = 8192
        assertTrue("ch0 interior SNR", snrDb(x0, out0, guard, t - guard) > 80.0)
        assertTrue("ch1 interior SNR", snrDb(x1, out1, guard, t - guard) > 80.0)
    }

    // ---- (4) le / frame arithmetic ----

    @Test fun frameArithmetic() {
        val stft = Stft(4096, 1024)
        assertEquals(2048, stft.bins)                  // nfft/2, Nyquist dropped
        assertEquals(336, stft.le(343_980))            // ceil(343980/1024) = 336, the production SEG
        assertEquals(335, stft.le(335 * 1024))         // exact multiple → no round up
        assertEquals(336, stft.le(335 * 1024 + 1))     // one sample over → an extra frame
        assertEquals(337, stft.le(336 * 1024 + 1))     // ceils past the next multiple
        assertEquals(258, Stft(64, 16).le(4123))       // small-config golden le
        assertEquals(32, Stft(64, 16).bins)
    }

    // ---- helpers ----

    private fun naiveDft(re: FloatArray, im: FloatArray): Pair<DoubleArray, DoubleArray> {
        val n = re.size
        val outRe = DoubleArray(n)
        val outIm = DoubleArray(n)
        for (k in 0 until n) {
            var sr = 0.0
            var si = 0.0
            for (j in 0 until n) {
                val ang = -2.0 * PI * k * j / n
                val c = cos(ang)
                val s = sin(ang)
                sr += re[j] * c - im[j] * s
                si += re[j] * s + im[j] * c
            }
            outRe[k] = sr
            outIm[k] = si
        }
        return outRe to outIm
    }

    // Deterministic band-limited stereo probe: a sum of low-frequency sinusoids (negligible energy near
    // Nyquist), peak-normalized to 0.5. Such a signal survives the Nyquist-dropping model STFT.
    private fun bandLimited(t: Int, seed: Long): FloatArray {
        val rng = Random(seed)
        val acc = DoubleArray(t)
        repeat(40) {
            val freq = 0.0005 + rng.nextDouble() * (0.05 - 0.0005)   // cycles/sample, far below Nyquist (0.5)
            val amp = rng.nextDouble() * 2 - 1
            val phase = rng.nextDouble() * 2 * PI
            for (n in 0 until t) acc[n] += amp * sin(2.0 * PI * freq * n + phase)
        }
        var peak = 0.0
        for (v in acc) peak = maxOf(peak, abs(v))
        val scale = 0.5 / peak
        return FloatArray(t) { (acc[it] * scale).toFloat() }
    }

    private fun snrDb(ref: FloatArray, rec: FloatArray, from: Int, to: Int): Double {
        var signal = 0.0
        var error = 0.0
        for (i in from until to) {
            val r = ref[i].toDouble()
            val e = r - rec[i].toDouble()
            signal += r * r
            error += e * e
        }
        return 10.0 * log10(signal / error)   // 10·log10 of the power ratio
    }

    private fun assertMaxAbsDiff(expected: DoubleArray, actual: FloatArray, atol: Double) {
        assertEquals(expected.size, actual.size)
        var maxDiff = 0.0
        var at = -1
        for (i in expected.indices) {
            val d = abs(expected[i] - actual[i].toDouble())
            if (d > maxDiff) {
                maxDiff = d
                at = i
            }
        }
        assertTrue("max abs diff $maxDiff at index $at exceeds $atol", maxDiff <= atol)
    }

    private fun golden(): Golden {
        val text = javaClass.getResourceAsStream("/dsp/stft_small.json")!!
            .bufferedReader().use { it.readText() }
        val o = JSONObject(text)
        val input = o.getJSONArray("input")
        val roundtrip = o.getJSONArray("roundtrip")
        return Golden(
            nfft = o.getInt("nfft"),
            hop = o.getInt("hop"),
            t = o.getInt("T"),
            input0 = toFloatArray(input.getJSONArray(0)),
            input1 = toFloatArray(input.getJSONArray(1)),
            cac = toDoubleArray(o.getJSONArray("cac")),
            roundtrip0 = toDoubleArray(roundtrip.getJSONArray(0)),
            roundtrip1 = toDoubleArray(roundtrip.getJSONArray(1)),
        )
    }

    private fun toFloatArray(a: JSONArray) = FloatArray(a.length()) { a.getDouble(it).toFloat() }
    private fun toDoubleArray(a: JSONArray) = DoubleArray(a.length()) { a.getDouble(it) }

    private class Golden(
        val nfft: Int,
        val hop: Int,
        val t: Int,
        val input0: FloatArray,
        val input1: FloatArray,
        val cac: DoubleArray,
        val roundtrip0: DoubleArray,
        val roundtrip1: DoubleArray,
    )
}
